# Generated by Django 6.0.8 on 2026-09-06 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=160)),
                ('actividad_economica', models.CharField(blank=True, max_length=80)),
                ('correo_reportes', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(default='activo', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_afectada', models.CharField(max_length=30)),
                ('id_registro', models.IntegerField()),
                ('accion', models.CharField(max_length=12)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=160)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnvioReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('correo_destino', models.EmailField(max_length=254)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado_envio', models.CharField(default='enviado', max_length=12)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('proveedor', models.CharField(max_length=120)),
                ('concepto', models.CharField(blank=True, max_length=160)),
                ('estado', models.CharField(default='vigente', max_length=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('propietario', 'Propietario'), ('dependiente', 'Dependiente')], default='dependiente', max_length=20)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.establecimiento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('fuente', 'Retención en la fuente'), ('ica', 'Retención de ICA')], default='ica', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tercero', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(default='vigente', max_length=12)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.establecimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('concepto', models.CharField(max_length=160)),
                ('observacion', models.CharField(blank=True, max_length=160)),
                ('estado', models.CharField(default='vigente', max_length=12)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.establecimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
