# Generated by Django 6.0.8 on 2026-09-06 22:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retencion', to='registro.venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venta',
            name='ica_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_cliente',
            field=models.CharField(choices=[('particular', 'Particular'), ('empresa', 'Empresa')], default='particular', max_length=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='concepto',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='ActividadCIIU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej. 4711', max_length=10)),
                ('descripcion', models.CharField(max_length=160)),
                ('tarifa_x_mil', models.DecimalField(decimal_places=2, help_text='Tarifa ICA, por mil. Ej. 6 = 6 x mil', max_digits=6)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='registro.establecimiento')),
            ],
            options={
                'unique_together': {('establecimiento', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registro.actividadciiu'),
        ),
        migrations.CreateModel(
            name='MotivoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos', to='registro.actividadciiu')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos', to='registro.establecimiento')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registro.motivoventa'),
        ),
    ]
