# Generated by Django 6.0.8 on 2026-09-08 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_retencion_venta_venta_fecha_hora_venta_ica_estimado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='envioreporte',
            name='total_ica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='envioreporte',
            name='total_retenciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='id_registro',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['establecimiento', 'fecha'], name='compra_est_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='retencion',
            index=models.Index(fields=['establecimiento', 'fecha'], name='ret_est_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['establecimiento', 'fecha'], name='venta_est_fecha_idx'),
        ),
    ]
