# Generated by Django 6.0.8 on 2026-09-23 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_indices_envio_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('carnes', 'Carnes y Derivados'), ('viveres', 'Víveres y Abarrotes'), ('lacteos', 'Lácteos'), ('bebidas', 'Bebidas'), ('otros', 'Otros')], default='carnes', max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('stock_kilos', models.DecimalField(decimal_places=2, default=0, help_text='Existencias en Kilogramos', max_digits=10)),
                ('precio_kilo', models.DecimalField(decimal_places=2, help_text='Precio por Kilo', max_digits=12)),
                ('estado', models.CharField(default='activo', max_length=12)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='registro.establecimiento')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
