# Generated by Django 6.0.8 on 2026-09-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_kilos',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Existencias en Kilogramos con precisión de gramos', max_digits=12),
        ),
    ]
