# Generated by Django 6.0.8 on 2026-09-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_producto_stock_kilos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('carnes', 'Carnes y Embutidos'), ('abarrotes', 'Víveres y Abarrotes'), ('lacteos', 'Lácteos y Huevos'), ('fruver', 'Frutas y Verduras'), ('bebidas', 'Bebidas'), ('aseo', 'Aseo y Limpieza'), ('otros', 'Otros')], default='carnes', max_length=20),
        ),
    ]
