# Generated by Django 6.0.8 on 2026-09-23 00:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('carnes', 'Carnes y Embutidos'), ('abarrotes', 'Víveres y Abarrotes'), ('lacteos', 'Lácteos y Huevos'), ('fruver', 'Frutas y Verduras'), ('bebidas', 'Bebidas'), ('aseo', 'Aseo y Limpieza'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('cantidad_sugerida', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Cantidad sugerida a comprar', max_digits=10)),
                ('unidad', models.CharField(default='Kg', help_text='Kg, lb, unidades, cubeta, etc.', max_length=20)),
                ('origen', models.CharField(choices=[('agotado', 'Inventario Agotado / Por Reponer'), ('stock_bajo', 'Stock Bajo'), ('solicitado', 'Solicitado por Cliente (No existe en catálogo)'), ('manual', 'Agregado Manualmente')], default='agotado', max_length=20)),
                ('veces_solicitado', models.PositiveIntegerField(default=1, help_text='Número de veces que fue solicitado o consultado')),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente por comprar'), ('comprado', 'Comprado'), ('descartado', 'Descartado')], default='pendiente', max_length=15)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_compra', to='registro.establecimiento')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='registro.producto')),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
