# Generated by Django 6.0.8 on 2026-09-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
    ]
