# Generated by Django 6.0.8 on 2026-09-25 05:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_venta_medio_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=20)),
                ('identificador_mensaje', models.CharField(db_index=True, max_length=128, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('respuesta_cacheada', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(db_index=True, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('departamento', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='banco_receptor_bre_b',
            field=models.CharField(blank=True, help_text='Entidad financiera receptora', max_length=80),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='bono_incentivo_acumulado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='fecha_fin_prueba',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='llave_bre_b',
            field=models.CharField(blank=True, help_text='Celular, NIT o Alias Bre-B registrado', max_length=60),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='modo_operacion',
            field=models.CharField(choices=[('nativo', 'Modo Nativo (POS Principal)'), ('shadow', 'Modo Shadow (Intercepta POS Legacy)')], default='nativo', max_length=20),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='plan_suscripcion',
            field=models.CharField(choices=[('lanzamiento_cero', 'Plan $0 (Lanzamiento / Prueba)'), ('activo', 'Activo (Al Día)'), ('mora', 'En Mora'), ('suspendido', 'Suspendido')], default='lanzamiento_cero', max_length=20),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_llave_bre_b',
            field=models.CharField(default='celular', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('transferencia', 'Transferencia'), ('bre_b', 'Bre-B')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimientos', to='registro.municipio'),
        ),
        migrations.CreateModel(
            name='ReglaTributariaMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_avisos_y_tableros', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='% sobre impuesto neto ICA (Ley 97/1913)', max_digits=5)),
                ('porcentaje_sobretasa_bomberil', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='% sobre impuesto neto ICA (Ley 1575/2012)', max_digits=5)),
                ('base_minima_declarante_uvt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 si declara desde el primer peso', max_digits=10)),
                ('meses_periodo_ica', models.PositiveSmallIntegerField(default=2, help_text='2 para bimestral (Tunja régimen común), 12 para anual')),
                ('acuerdo_municipal_referencia', models.CharField(default='Acuerdo 0032 de 2020', help_text='Norma local vigente', max_length=100)),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regla_ica', to='registro.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='TokenVinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('expira', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.establecimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, db_index=True, help_text='WhatsApp celular', max_length=20)),
                ('nit_cedula', models.CharField(blank=True, help_text='Cédula o NIT para soporte fiscal', max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=160)),
                ('punto_referencia', models.CharField(blank=True, help_text="Crucial en barrios: 'frente a la panadería, reja negra'", max_length=160)),
                ('saldo_fiado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cupo_credito_maximo', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_pedido', models.DateTimeField(blank=True, null=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='registro.establecimiento')),
            ],
            options={
                'indexes': [models.Index(fields=['establecimiento', 'telefono'], name='cliente_est_tel_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistroExogenaMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_gravable', models.PositiveIntegerField(default=2026)),
                ('tipo_registro', models.CharField(choices=[('compra', 'Compras y Servicios Recibidos'), ('venta', 'Ingresos Obtenidos por Tercero'), ('reteica_practicado', 'Retenciones de ICA Practicadas'), ('reteica_asumido', 'Retenciones de ICA que le practicaron')], max_length=25)),
                ('nit_tercero', models.CharField(db_index=True, max_length=20)),
                ('nombre_razon_social', models.CharField(max_length=160)),
                ('direccion_tercero', models.CharField(blank=True, max_length=160)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_impuesto_retencion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tarifa_aplicada', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('fecha_transaccion', models.DateField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_exogena', to='registro.establecimiento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.municipio')),
            ],
            options={
                'indexes': [models.Index(fields=['establecimiento', 'año_gravable', 'tipo_registro'], name='exogena_est_año_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransaccionBreB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_unica', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_visual_corto', models.CharField(blank=True, help_text='Micro-token de 3 dígitos (ej: #819) para validación en mostrador', max_length=8)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('llave_utilizada', models.CharField(max_length=60)),
                ('id_transaccion_banrep', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('banco_origen', models.CharField(blank=True, max_length=80)),
                ('payload_emvco', models.TextField(blank=True)),
                ('comando_original', models.CharField(blank=True, max_length=160)),
                ('estado', models.CharField(choices=[('iniciada', 'Esperando Pago'), ('aprobada', 'Aprobada y Liquidada'), ('rechazada', 'Rechazada por Banco'), ('expirada', 'Expirada')], default='iniciada', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_bre_b', to='registro.establecimiento')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_bre_b', to='registro.venta')),
            ],
            options={
                'indexes': [models.Index(fields=['referencia_unica', 'estado'], name='breb_ref_est_idx')],
            },
        ),
        migrations.CreateModel(
            name='VinculoCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=20)),
                ('identificador_externo', models.CharField(db_index=True, help_text='chat_id de Telegram o número telefónico de WhatsApp', max_length=64)),
                ('username_externo', models.CharField(blank=True, max_length=80)),
                ('nombre_remitente', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_canal', to='registro.establecimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_canal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['canal', 'identificador_externo'], name='vinculo_canal_idx')],
                'unique_together': {('canal', 'identificador_externo')},
            },
        ),
    ]
