# Generated by Django 6.0.8 on 2026-09-25 16:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_mensajeprocesado_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras EAN-13, SKU o referencia', max_length=64),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Costo de compra al proveedor', max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_servicio',
            field=models.BooleanField(default=False, help_text='Marcar si es un servicio o mano de obra sin control de stock físico'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(default='kg', help_text='kg, lb, und, paquete, servicio', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='comprobante_bancario',
            field=models.CharField(blank=True, help_text='N° de comprobante / aprobación electrónica', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='conciliado_banco',
            field=models.BooleanField(default=False, help_text='Verificado contra extracto bancario o riel'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_conciliacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de verificación en extracto', null=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='categoria',
            field=models.CharField(choices=[('carnes', 'Carnes y Embutidos'), ('abarrotes', 'Víveres y Abarrotes'), ('lacteos', 'Lácteos y Huevos'), ('fruver', 'Frutas y Verduras'), ('bebidas', 'Bebidas'), ('aseo', 'Aseo y Limpieza'), ('servicios', 'Servicios y Mano de Obra'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('carnes', 'Carnes y Embutidos'), ('abarrotes', 'Víveres y Abarrotes'), ('lacteos', 'Lácteos y Huevos'), ('fruver', 'Frutas y Verduras'), ('bebidas', 'Bebidas'), ('aseo', 'Aseo y Limpieza'), ('servicios', 'Servicios y Mano de Obra'), ('otros', 'Otros')], default='carnes', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_kilo',
            field=models.DecimalField(decimal_places=2, help_text='Precio por Kilo o Unidad', max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_kilos',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Existencias en Kilogramos o Unidades', max_digits=12),
        ),
    ]
