# Generated by Django 6.0.8 on 2026-09-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_producto_codigo_barras_producto_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='registro.establecimiento'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
