# Generated by Django 6.0.8 on 2026-09-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_auditoria_establecimiento_alter_auditoria_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(blank=True, help_text='Obligatorio por la DIAN para entrega de factura electrónica', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamento_nombre',
            field=models.CharField(blank=True, default='Boyacá', max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dv',
            field=models.CharField(blank=True, help_text='Dígito de verificación (solo si es NIT)', max_length=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_consumidor_final',
            field=models.BooleanField(default=False, help_text='True si corresponde al Consumidor Final de mostrador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio_nombre',
            field=models.CharField(blank=True, default='Tunja', max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.CharField(choices=[('no_responsable_iva', 'No responsable de IVA (Persona Natural)'), ('responsable_iva', 'Responsable de IVA (Común)'), ('simple', 'Régimen Simple de Tributación (RST)'), ('gran_contribuyente', 'Gran Contribuyente')], default='no_responsable_iva', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('13', 'Cédula de Ciudadanía (CC)'), ('31', 'NIT (Número de Identificación Tributaria)'), ('22', 'Cédula de Extranjería (CE)'), ('41', 'Pasaporte'), ('42', 'Documento de Identificación Extranjero'), ('47', 'Permiso por Protección Temporal (PPT)')], default='13', help_text='Tipo de documento según catálogo DIAN', max_length=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=15),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='consecutivo_actual',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='facturacion_electronica_habilitada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='prefijo_facturacion',
            field=models.CharField(blank=True, default='FE', help_text='Prefijo asignado por la DIAN (ej: FE)', max_length=10),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='rango_desde',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='rango_hasta',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='resolucion_dian_numero',
            field=models.CharField(blank=True, default='18764000001', help_text='Resolución DIAN de Facturación', max_length=60),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='registro.cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cufe',
            field=models.CharField(blank=True, help_text='Código Único de Facturación Electrónica DIAN', max_length=120),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_dian',
            field=models.CharField(choices=[('no_requerida', 'Consumidor Final (No requerida)'), ('pendiente', 'Pendiente Envío DIAN'), ('aprobada', 'Aprobada DIAN'), ('rechazada', 'Rechazada DIAN')], default='no_requerida', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_factura_electronica',
            field=models.CharField(blank=True, help_text='Número consecutivo fiscal (ej: FE-00142)', max_length=30),
        ),
        migrations.AddField(
            model_name='venta',
            name='solicita_factura_electronica',
            field=models.BooleanField(default=False, help_text='Cliente solicitó Factura Electrónica con reporte individual DIAN'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, default='Tunja, Boyacá', max_length=160),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit_cedula',
            field=models.CharField(db_index=True, default='222222222222', help_text='Cédula, NIT o 222222222222 para Consumidor Final', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Nombre completo o Razón Social del cliente', max_length=120),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['establecimiento', 'nit_cedula'], name='cliente_est_nit_idx'),
        ),
    ]
