# Generated by Django 6.0.8 on 2026-09-25 16:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_cliente_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='anticipo_ano_anterior',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Renglón 29: Menos anticipo liquidado en el año anterior', max_digits=14),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='clasificacion_tributaria',
            field=models.CharField(choices=[('comun', 'Régimen Común / Ordinario (Bimestral)'), ('simplificado', 'Régimen Simplificado (Anual)'), ('simple_rst', 'Régimen Simple de Tributación (RST)')], default='comun', help_text='Clasificación tributaria en el municipio', max_length=30),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='configuracion_inicial_completada',
            field=models.BooleanField(default=False, help_text='Indica si completó el asistente inicial de declaración renglón a renglón'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='matricula_mercantil',
            field=models.CharField(blank=True, help_text='Matrícula mercantil Cámara de Comercio (ej: TUN-012345)', max_length=40),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='saldo_favor_anterior',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Renglón 32: Menos saldo a favor del periodo anterior', max_digits=14),
        ),
    ]
