# Generated by Django 6.0.8 on 2026-09-25 16:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_establecimiento_anticipo_ano_anterior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='declara_renta_dian',
            field=models.BooleanField(default=False, help_text='Indica si el comerciante declara impuesto de Renta ante la DIAN'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='otros_ingresos_nacionales_anual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Renglón 9: Otros ingresos anuales brutos fuera de este municipio o de otras sedes', max_digits=14),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='propietario_creador',
            field=models.ForeignKey(blank=True, help_text='Usuario dueño que creó y administra este establecimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('empresario', 'Empresario Multi-Establecimiento'), ('propietario', 'Propietario'), ('dependiente', 'Dependiente')], default='dependiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
