# Generated by Django 6.0.8 on 2026-09-25 17:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_establecimiento_declara_renta_dian_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('19900'), max_digits=12)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('periodo_dias', models.PositiveIntegerField(default=30, help_text='Días de vigencia añadidos')),
                ('metodo', models.CharField(choices=[('bre_b', 'Bre-B (BanRep Interoperable)'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo / Cobro Directo'), ('cortesia', 'Cortesía / Promoción')], default='bre_b', max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Comprobante bancario o ID de transacción', max_length=80)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_suscripcion', to='registro.establecimiento')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
