# Generated by Django 6.0.8 on 2026-09-25 20:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_pagosuscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPlataformaSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave_bre_b_general', models.CharField(default='3028530041', help_text='Llave Bre-B / BanRep / Nequi oficial para cobro de suscripciones a comercios', max_length=60)),
                ('tipo_llave_bre_b', models.CharField(default='celular', max_length=20)),
                ('banco_receptor', models.CharField(blank=True, default='Bancolombia / Nequi', max_length=80)),
                ('whatsapp_soporte_general', models.CharField(default='3146922087', help_text='WhatsApp técnico y de contacto soporte de la plataforma', max_length=40)),
                ('tarifa_mensual_cop', models.DecimalField(decimal_places=2, default=Decimal('19900'), help_text='Tarifa plana de suscripción mensual estándar ($19.900 COP)', max_digits=12)),
                ('correo_soporte', models.EmailField(blank=True, default='soporte@diariocomercial.co', max_length=254)),
                ('smtp_activo', models.BooleanField(default=False, help_text='Activar envío de correos vía SMTP real (si está inactivo, usa backend de consola)')),
                ('smtp_host', models.CharField(blank=True, default='smtp-relay.brevo.com', max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=120)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=120)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_from_email', models.EmailField(blank=True, default='soporte@diariocomercial.co', max_length=254)),
                ('dias_gracia_mora', models.PositiveIntegerField(default=5, help_text='Días de gracia antes de suspender comercio tras vencimiento')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global SaaS',
                'verbose_name_plural': 'Configuración Global SaaS',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSaaSMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave_bre_b', models.CharField(blank=True, help_text='Llave Bre-B exclusiva para recaudos en este municipio (dejar en blanco para usar la general)', max_length=60)),
                ('tipo_llave_bre_b', models.CharField(default='celular', max_length=20)),
                ('banco_receptor', models.CharField(blank=True, max_length=80)),
                ('whatsapp_soporte', models.CharField(blank=True, help_text='WhatsApp de contacto/soporte exclusivo para este municipio (dejar en blanco para usar el general)', max_length=40)),
                ('tarifa_mensual_cop', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa mensual diferenciada para este municipio (dejar en blanco para estándar $19.900)', max_digits=12, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_saas_segmentada', to='registro.municipio')),
            ],
            options={
                'verbose_name': 'Segmentación SaaS por Municipio',
                'verbose_name_plural': 'Segmentaciones SaaS por Municipio',
                'ordering': ['municipio__nombre'],
            },
        ),
    ]
