# Generated by Django 6.0.8 on 2026-09-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_configuracionplataformasaas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='frecuencia_reporte_automatico',
            field=models.CharField(choices=[('desactivado', 'Desactivado'), ('hora', 'Cada Hora'), ('turno', 'Cada Medio Día / Turno (12 horas)'), ('diario', 'Diario (Cierre del día)'), ('semanal', 'Semanal (Cierre de semana)'), ('mensual', 'Mensual (Cierre de mes)')], default='diario', help_text='Frecuencia periódica de generación y despacho de reportes en Excel', max_length=20),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='reportes_automaticos_activos',
            field=models.BooleanField(default=False, help_text='Activa el envío periódico automático de reportes en Excel al correo registrado'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='ultimo_reporte_automatico',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última ejecución automática de despacho de reporte', null=True),
        ),
    ]
