# Generated by Django 6.0.8 on 2026-09-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0017_establecimiento_frecuencia_reporte_automatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Teléfono o celular de contacto del establecimiento', max_length=30),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_negocio',
            field=models.CharField(blank=True, choices=[('carniceria', 'Carnicería / Fama'), ('minimarket', 'Minimarket / Supermercado / Abarrotes'), ('drogueria', 'Droguería / Farmacia'), ('panaderia', 'Panadería / Cafetería'), ('restaurante', 'Restaurante / Bar'), ('ferreteria', 'Ferretería / Eléctricos'), ('servicios', 'Servicios Profesionales / Técnicos'), ('otro', 'Otro Comercio')], default='minimarket', help_text='Giro o tipo de negocio para preconfiguración contable y catálogo', max_length=40),
        ),
        migrations.AddField(
            model_name='perfil',
            name='documento_identidad',
            field=models.CharField(blank=True, help_text='Cédula de ciudadanía o documento', max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono o celular personal / WhatsApp', max_length=30),
        ),
    ]
