# Generated by Django 6.0.8 on 2026-09-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0018_establecimiento_telefono_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('11', 'Registro Civil'), ('12', 'Tarjeta de Identidad'), ('13', 'Cédula de Ciudadanía (CC)'), ('21', 'Tarjeta de Extranjería'), ('22', 'Cédula de Extranjería (CE)'), ('31', 'NIT (Número de Identificación Tributaria)'), ('41', 'Pasaporte'), ('42', 'Documento de Identificación Extranjero'), ('47', 'Permiso por Protección Temporal (PPT)')], default='13', help_text='Tipo de documento según catálogo DIAN', max_length=5),
        ),
    ]
