# Generated by Django 6.0.8 on 2026-09-26 17:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0019_alter_cliente_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Cantidad vendida en la unidad correspondiente (gramos, unidades o ml)', max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='registro.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='unidad_medida',
            field=models.CharField(default='und', help_text='g, kg, lb, und, ml, lt, etc.', max_length=20),
        ),
    ]
