# Generated by Django 6.0.8 on 2026-09-27 13:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0020_venta_cantidad_venta_producto_venta_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='costo_domicilio_defecto',
            field=models.DecimalField(decimal_places=2, default=Decimal('3000'), help_text='Tarifa base de domicilio de barrio en pesos COP', max_digits=10),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='impresion_automatica_pedidos',
            field=models.BooleanField(default=True, help_text='Habilita el encolamiento automático de comandas térmicas para la impresora POS'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='monto_minimo_domicilio_gratis',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000'), help_text='Monto mínimo para envío gratis (upselling en WhatsApp)', max_digits=12),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.PositiveIntegerField(db_index=True)),
                ('canal_origen', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('web', 'Panel Web / KDS'), ('mostrador', 'Mostrador / Teléfono')], default='whatsapp', max_length=20)),
                ('telefono_contacto', models.CharField(db_index=True, help_text='Celular WhatsApp del cliente', max_length=25)),
                ('nombre_contacto', models.CharField(blank=True, max_length=120)),
                ('direccion_entrega', models.CharField(help_text='Dirección o barrio de entrega', max_length=200)),
                ('punto_referencia', models.CharField(blank=True, help_text='Casa reja verde, frente al poste, etc.', max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('costo_domicilio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('medio_pago', models.CharField(choices=[('pendiente', 'Pendiente por definir'), ('efectivo', 'Efectivo Contra Entrega'), ('bre_b', 'Bre-B (Interoperable BanRep)'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('transferencia', 'Transferencia Bancaria')], default='pendiente', max_length=20)),
                ('paga_con', models.DecimalField(blank=True, decimal_places=2, help_text='Monto con el que paga en efectivo (ej: 50.000) para calcular vueltas', max_digits=14, null=True)),
                ('vueltas', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Vueltas a enviar al cliente (paga_con - total)', max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('cotizado', 'Cotizado / Esperando Confirmación'), ('esperando_pago', 'Esperando Pago Digital'), ('pagado', 'Pagado / En Preparación'), ('en_preparacion', 'En Preparación'), ('en_camino', 'En Camino / Despachado'), ('entregado', 'Entregado y Liquidado'), ('cancelado', 'Cancelado')], db_index=True, default='borrador', max_length=25)),
                ('impreso_pos', models.BooleanField(db_index=True, default=False, help_text='True si ya fue impreso en el POS')),
                ('fecha_impresion', models.DateTimeField(blank=True, null=True)),
                ('veces_impreso', models.PositiveSmallIntegerField(default=0)),
                ('nombre_domiciliario', models.CharField(blank=True, help_text='Nombre de quien entrega el pedido', max_length=80)),
                ('notas_operativas', models.TextField(blank=True, help_text='Instrucciones especiales de cocina o empaque')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_domicilio', to='registro.cliente')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='registro.establecimiento')),
                ('transaccion_bre_b', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='registro.transaccionbreb')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='registro.venta')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=120)),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('unidad_medida', models.CharField(default='und', max_length=15)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notas', models.CharField(blank=True, help_text="Ej: 'bien tajado', 'poca grasa'", max_length=140)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='registro.pedido')),
            ],
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['establecimiento', 'estado', 'fecha_creacion'], name='pedido_est_fec_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['establecimiento', 'impreso_pos'], name='pedido_imp_pos_idx'),
        ),
    ]
