# Generated by Django 6.0.8 on 2026-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0021_establecimiento_costo_domicilio_defecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='domicilio_hora_apertura',
            field=models.TimeField(default='07:00:00', help_text='Hora de inicio del servicio de domicilios (ej: 07:00)'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='domicilio_hora_cierre',
            field=models.TimeField(default='21:00:00', help_text='Hora de finalización del servicio de domicilios (ej: 21:00)'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='domicilio_mensaje_pausa',
            field=models.CharField(blank=True, default='', help_text="Motivo temporal de pausa opcional (ej: 'Alta congestión por lluvia')", max_length=200),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='domicilio_programar_horario',
            field=models.BooleanField(default=False, help_text='Activa el control automático por franja horaria de atención'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='domicilios_activos',
            field=models.BooleanField(default=True, help_text='Interruptor maestro para encender o apagar el servicio de domicilios'),
        ),
    ]
