# Generated by Django 6.0.8 on 2026-09-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0022_establecimiento_domicilio_hora_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='recojo_tienda_activo',
            field=models.BooleanField(default=True, help_text='Permite pedidos en línea para recoger en tienda física / mostrador'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='recojo_tienda_mensaje_pausa',
            field=models.CharField(blank=True, default='', help_text='Motivo temporal si se pausa el servicio de recojo en tienda', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('domicilio', 'Domicilio a Dirección'), ('recojo_tienda', 'Recojo en Tienda / Para Llevar')], db_index=True, default='domicilio', help_text='Modalidad: domicilio a dirección o recojo en tienda física', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('cotizado', 'Cotizado / Esperando Confirmación'), ('esperando_pago', 'Esperando Pago Digital'), ('pagado', 'Pagado / En Preparación'), ('en_preparacion', 'En Preparación'), ('listo_para_recoger', 'Listo para Recoger en Tienda'), ('en_camino', 'En Camino / Despachado'), ('entregado', 'Entregado y Liquidado'), ('cancelado', 'Cancelado')], db_index=True, default='borrador', max_length=25),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['establecimiento', 'tipo_entrega'], name='pedido_est_tipo_idx'),
        ),
    ]
