# Generated by Django 6.0.8 on 2026-09-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0023_establecimiento_recojo_tienda_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_corto',
            field=models.CharField(blank=True, db_index=True, help_text='Código corto o PLU de marcación rápida para caja y pedidos de clientes (ej: 101, 2323)', max_length=20),
        ),
    ]
