# Generated by Django 6.0.8 on 2026-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0024_producto_codigo_corto'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='copias_impresion_defecto',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de copias a imprimir automáticamente por venta'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='formato_recibo',
            field=models.CharField(choices=[('ticket', 'Tirilla / Ticket de Venta Estándar'), ('factura_carta', 'Factura Completa Tamaño Carta'), ('media_carta', 'Comprobante Media Carta (Ahorro de papel en impresora normal)')], default='ticket', help_text='Formato de salida predeterminado', max_length=30),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='impresion_directa_ventas',
            field=models.BooleanField(default=False, help_text='Imprime automáticamente el ticket/factura apenas se genera una venta (sin clics adicionales)'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='nombre_impresora',
            field=models.CharField(blank=True, default='', help_text='Nombre de la impresora conectada (ej: Epson EcoTank L3210, Xprinter POS-80)', max_length=100),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_impresora',
            field=models.CharField(choices=[('normal', 'Impresora Normal de Oficina (Epson, HP, Canon - Carta / Media Carta)'), ('termica_80', 'Impresora Térmica de Rollo POS 80mm'), ('termica_58', 'Impresora Térmica de Rollo POS 58mm')], default='normal', help_text='Tipo de impresora principal conectada al equipo', max_length=30),
        ),
    ]
