# Generated by Django 6.0.8 on 2026-09-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0025_establecimiento_copias_impresion_defecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='cajon_apertura_automatica',
            field=models.BooleanField(default=True, help_text='Abre automáticamente el cajón al registrar ventas pagadas en efectivo'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='cajon_monedero_activo',
            field=models.BooleanField(default=True, help_text='Habilita el uso y control de cajón monedero en este negocio'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='cajon_pin',
            field=models.CharField(choices=[('pin2', 'Pin 2 (Estándar Epson, Xprinter, Star)'), ('pin5', 'Pin 5 (Secundario / Segundo cajón)')], default='pin2', help_text='Pin del conector RJ11 que recibe el pulso eléctrico', max_length=10),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='cajon_tipo_conexion',
            field=models.CharField(choices=[('impresora_rj11', 'Conectado a la Impresora (Cable RJ11 - Estándar ESC/POS)'), ('usb_directo', 'Conexión USB Directa / Puerto Serial'), ('manual', 'Apertura Manual con Llave')], default='impresora_rj11', help_text='Tipo de conexión física del cajón monedero', max_length=30),
        ),
        migrations.CreateModel(
            name='LectoraCodigoBarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo (ej: Pistola USB Mostrador 1, Honeywell Voyager)', max_length=100)),
                ('modelo_marca', models.CharField(blank=True, default='', help_text='Marca o modelo (ej: Xprinter, Honeywell, Netum, Zebra, Genérica)', max_length=100)),
                ('tipo_conexion', models.CharField(choices=[('usb_hid', 'USB Teclado Emulado (HID - Conectar y listo)'), ('bluetooth', 'Inalámbrico Bluetooth / 2.4 GHz'), ('serial_com', 'Puerto Serial / Virtual COM')], default='usb_hid', max_length=30)),
                ('sufijo', models.CharField(choices=[('enter', 'Enter / Retorno de carro (Estándar recomendado)'), ('tab', 'Tabulador (Tab)'), ('ninguno', 'Sin sufijo (Solo dígitos)')], default='enter', max_length=20)),
                ('beep_sonido', models.BooleanField(default=True, help_text="Emite sonido 'beep' de confirmación en el navegador al escanear")),
                ('auto_enter_busqueda', models.BooleanField(default=True, help_text='Dispara la búsqueda o suma automática del producto al recibir el código')),
                ('activo', models.BooleanField(default=True, help_text='Activa o desactiva la lectora')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectoras_codigo_barras', to='registro.establecimiento')),
            ],
            options={
                'verbose_name': 'Lectora de Código de Barras',
                'verbose_name_plural': 'Lectoras de Código de Barras',
                'ordering': ['-activo', 'nombre'],
            },
        ),
    ]
